
UPDATE public.projects SET
  titulo='MarmitaGest: SaaS Financeiro para Restaurantes',
  descricao='Plataforma focada na gestão financeira de restaurantes: faturamento, custos, lucro e indicadores semanais em um só lugar. Projeto Design Engineer pensado, desenhado e construído por mim do início ao fim.',
  contexto=E'Pequenos restaurantes ainda controlam o financeiro no caderno ou em planilhas dispersas. Esse processo manual gera erros de cálculo, perda de receita e dificulta enxergar com clareza o quanto realmente sobra no fim da semana.\n\nO MarmitaGest nasceu para resolver essa dor: dar ao dono do restaurante uma ferramenta simples, rápida e visual para acompanhar toda a saúde financeira do negócio em um só lugar.',
  objetivo='Construir um SaaS web e mobile dedicado à gestão financeira de restaurantes: registro de faturamento, custos e despesas, cálculo automático de lucro e painel com indicadores semanais. A proposta é entregar uma ferramenta acessível, intuitiva e visualmente acolhedora, mesmo para usuários com pouca familiaridade com tecnologia.',
  processo_research='Conversei com donos de restaurantes para entender como controlam o financeiro: como registram receitas, como acompanham custos fixos e variáveis e como calculam o lucro da semana. Identifiquei que o maior gargalo é a falta de visibilidade clara sobre o que realmente sobra no caixa.',
  processo_wireframe='Estruturei os fluxos principais: login → dashboard financeiro com KPIs → lançamento de receitas e custos → relatório semanal de desempenho. Priorizei poucas telas e ações de no máximo dois cliques para o dono operar com pressa no horário de pico.',
  processo_ui_design='Desenvolvi a identidade visual com laranja vibrante como cor principal, transmitindo apetite, energia e calor humano. Tipografia bold para os números, cards com hierarquia clara para os indicadores financeiros e gráficos limpos. Layout responsivo, do MacBook ao iPhone, com a mesma experiência fluida.',
  resultado='App pensado e construído inteiramente por mim, do descobrimento ao deploy. Plataforma no ar com dashboard financeiro, lançamento de receitas e custos, cálculo de lucro e painel semanal de desempenho. Projeto Design Engineer ponta a ponta: research, UI design, frontend, backend e publicação.',
  titulo_en='MarmitaGest: Financial SaaS for Restaurants',
  descricao_en='Platform focused on financial management for restaurants: revenue, costs, profit and weekly indicators in one place. A Design Engineer project I thought through, designed and built end-to-end.',
  contexto_en=E'Small restaurants still track finances on paper or scattered spreadsheets. This manual process leads to calculation errors, lost revenue and makes it hard to clearly see how much is actually left at the end of the week.\n\nMarmitaGest was created to solve this pain: give the restaurant owner a simple, fast and visual tool to monitor the financial health of the business in one place.',
  objetivo_en='Build a web and mobile SaaS dedicated to financial management for restaurants: revenue tracking, costs and expenses, automatic profit calculation and a dashboard with weekly indicators. The goal is an accessible, intuitive and visually warm tool, even for users with low tech familiarity.',
  resultado_en='App thought through and built entirely by me, from discovery to deploy. Live platform with a financial dashboard, revenue and cost entries, profit calculation and a weekly performance panel. End-to-end Design Engineer project: research, UI design, frontend, backend and publishing.',
  processo_research_en='I talked to restaurant owners to understand how they handle their finances: how they record revenue, track fixed and variable costs and calculate weekly profit. I found that the biggest bottleneck is the lack of clear visibility on what is actually left in the cash flow.',
  processo_wireframe_en='I structured the main flows: login → financial dashboard with KPIs → revenue and cost entries → weekly performance report. I prioritized few screens and max-two-click actions so the owner can operate quickly during rush hour.',
  processo_ui_design_en='I developed the visual identity with vibrant orange as the main color, conveying appetite, energy and human warmth. Bold typography for numbers, cards with clear hierarchy for financial indicators and clean charts. Responsive layout from MacBook to iPhone with the same fluid experience.'
WHERE slug='marmitagest';
