
UPDATE public.projects SET
  titulo='MarmitaGest: SaaS para Gestão de Restaurantes',
  descricao='Plataforma completa para restaurantes gerenciarem pedidos, clientes e financeiro. Projeto Design Engineer pensado, desenhado e construído por mim do início ao fim. Em breve disponível na App Store e Play Store.',
  ferramentas=ARRAY['Figma','Lovable','Cursor','React','Tailwind CSS','Supabase'],
  contexto=E'Pequenos restaurantes ainda gerenciam pedidos, clientes e finanças no caderno ou em planilhas dispersas. Esse processo manual gera erros, esquecimento de entregas, perda de receita e dificulta o crescimento do negócio.\n\nO MarmitaGest nasceu para resolver essa dor: dar ao dono do restaurante uma ferramenta simples, rápida e visual para organizar todo o operacional do dia a dia em um só lugar.',
  objetivo='Construir um SaaS web e mobile que centralize a operação de um restaurante: gestão de pedidos com status em tempo real, base de clientes com histórico e painel financeiro com indicadores semanais. A proposta é entregar uma ferramenta acessível, intuitiva e visualmente acolhedora, mesmo para usuários com pouca familiaridade com tecnologia. Em breve o app estará disponível na App Store e na Play Store.',
  processo_research='Conversei com donos de restaurantes para entender o fluxo real: como recebem pedidos (WhatsApp, ligação), como controlam entregas, como cobram e como calculam o faturamento da semana. Identifiquei que o maior gargalo é a falta de visibilidade do que entra e sai por dia.',
  processo_wireframe='Estruturei os fluxos principais: login → dashboard com KPIs → criação de pedido → acompanhamento de status → base de clientes → relatório financeiro. Priorizei poucas telas e ações de no máximo dois cliques para o dono operar com pressa no horário de pico.',
  processo_ui_design='Desenvolvi a identidade visual com laranja vibrante como cor principal, transmitindo apetite, energia e calor humano. Tipografia bold para os números, cards com hierarquia clara e badges coloridos para status de pedido. Layout responsivo, do MacBook ao iPhone, com a mesma experiência fluida.',
  resultado='App pensado e construído inteiramente por mim, do descobrimento ao deploy. Plataforma no ar com dashboard de métricas, gestão de pedidos, base de clientes e painel financeiro semanal. Em breve disponível na App Store e Play Store. Projeto Design Engineer ponta a ponta: research, UI design, frontend, backend e publicação.',
  titulo_en='MarmitaGest: SaaS for Restaurant Management',
  descricao_en='Complete platform for restaurants to manage orders, customers and finances. A Design Engineer project I thought through, designed and built end-to-end. Coming soon to the App Store and Play Store.',
  contexto_en=E'Small restaurants still manage orders, customers and finances on paper or scattered spreadsheets. This manual process causes errors, missed deliveries, lost revenue and blocks business growth.\n\nMarmitaGest was created to solve this pain: give the owner a simple, fast and visual tool to organize the entire daily operation in one place.',
  objetivo_en='Build a web and mobile SaaS that centralizes the operation of a restaurant: real-time order tracking, customer base with history and a financial dashboard with weekly KPIs. The goal is an accessible, intuitive and visually warm tool, even for users with low tech familiarity. The app will soon be available on the App Store and Play Store.',
  resultado_en='App thought through and built entirely by me, from discovery to deploy. Live platform with metrics dashboard, order management, customer base and weekly financial panel. Coming soon to the App Store and Play Store. End-to-end Design Engineer project: research, UI design, frontend, backend and publishing.',
  processo_research_en='I talked to local restaurant owners to understand the real flow: how they receive orders (WhatsApp, calls), how they track deliveries, how they charge and how they calculate weekly revenue. I found that the biggest bottleneck is the lack of visibility of daily inflows and outflows.',
  processo_wireframe_en='I structured the main flows: login → KPI dashboard → order creation → status tracking → customer base → financial report. I prioritized few screens and max-two-click actions so the owner can operate quickly during rush hour.',
  processo_ui_design_en='I developed the visual identity with vibrant orange as the main color, conveying appetite, energy and human warmth. Bold typography for numbers, cards with clear hierarchy and colorful status badges. Responsive layout from MacBook to iPhone with the same fluid experience.'
WHERE slug='marmitagest';
